name: mae_ban
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  go_router: ^14.2.0
  image_picker: ^1.1.1
  logger: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  dotted_border: ^2.1.0
  image: ^4.1.7
  otp_text_field: ^1.1.3
  jwt_decoder: ^2.0.1
  # timeline_tile: ^2.0.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  url_launcher: ^6.3.0
  # pull_to_refresh: ^2.0.0

  #loader animation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/mock/

    # - images/a_dot_ham.jpeg

  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansLao-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansLao-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansLao-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansLao-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansLao-ExtraBold.ttf
          weight: 800
